#ifndef ArduinoMsgCodec_h
#define ArduinoMsgCodec_h

/*******************************************************************
 * MRLCOMM FUNCTION GENERATED INTERFACE
 * this file was generated by ArduinoMsgCodec and ArduinoMsgCodec.h.template
 */

///// INO GENERATED DEFINITION BEGIN //////
// {publishMRLCommError Integer} 
#define PUBLISH_MRLCOMM_ERROR		1
// {getBoardInfo} 
#define GET_BOARD_INFO		2
// {publishBoardInfo BoardInfo} 
#define PUBLISH_BOARD_INFO		3
// {analogWrite int int} 
#define ANALOG_WRITE		4
// {controllerAttach Arduino int} 
#define CONTROLLER_ATTACH		5
// {createI2cDevice I2CControl int int} 
#define CREATE_I2C_DEVICE		6
// {customMsg int[]} 
#define CUSTOM_MSG		7
// {deviceAttach DeviceControl Object[]} 
#define DEVICE_ATTACH		8
// {deviceDetach DeviceControl} 
#define DEVICE_DETACH		9
// {digitalWrite int int} 
#define DIGITAL_WRITE		10
// {disableBoardStatus} 
#define DISABLE_BOARD_STATUS		11
// {disablePin int} 
#define DISABLE_PIN		12
// {disablePins} 
#define DISABLE_PINS		13
// {enableBoardStatus int} 
#define ENABLE_BOARD_STATUS		14
// {enablePin int int} 
#define ENABLE_PIN		15
// {getMrlPinType PinDefinition} 
#define GET_MRL_PIN_TYPE		16
// {heartbeat} 
#define HEARTBEAT		17
// {i2cRead I2CControl int int byte[] int} 
#define I2C_READ		18
// {i2cReturnData SensorData} 
#define I2C_RETURN_DATA		19
// {i2cWrite I2CControl int int byte[] int} 
#define I2C_WRITE		20
// {i2cWriteRead I2CControl int int byte[] int byte[] int} 
#define I2C_WRITE_READ		21
// {intsToString int[] int int} 
#define INTS_TO_STRING		22
// {isAttached} 
#define IS_ATTACHED		23
// {isRecording} 
#define IS_RECORDING		24
// {motorMove MotorControl} 
#define MOTOR_MOVE		25
// {motorMoveTo MotorControl} 
#define MOTOR_MOVE_TO		26
// {motorReset MotorControl} 
#define MOTOR_RESET		27
// {motorStop MotorControl} 
#define MOTOR_STOP		28
// {msgRoute} 
#define MSG_ROUTE		29
// {neoPixelSetAnimation NeoPixel int int int int int} 
#define NEO_PIXEL_SET_ANIMATION		30
// {neoPixelWriteMatrix NeoPixel List} 
#define NEO_PIXEL_WRITE_MATRIX		31
// {onSensorData SensorData} 
#define ON_SENSOR_DATA		32
// {pinMode int String} 
#define PIN_MODE		33
// {publishAttachedDevice String} 
#define PUBLISH_ATTACHED_DEVICE		34
// {publishBoardStatus BoardStatus} 
#define PUBLISH_BOARD_STATUS		35
// {publishCustomMsg int[]} 
#define PUBLISH_CUSTOM_MSG		36
// {publishDebug String} 
#define PUBLISH_DEBUG		37
// {publishMessageAck} 
#define PUBLISH_MESSAGE_ACK		38
// {publishPin PinData} 
#define PUBLISH_PIN		39
// {publishPinArray PinData[]} 
#define PUBLISH_PIN_ARRAY		40
// {publishPinDefinition PinDefinition} 
#define PUBLISH_PIN_DEFINITION		41
// {publishPulse Long} 
#define PUBLISH_PULSE		42
// {publishPulseStop Integer} 
#define PUBLISH_PULSE_STOP		43
// {publishSensorData SensorData} 
#define PUBLISH_SENSOR_DATA		44
// {publishServoEvent Integer} 
#define PUBLISH_SERVO_EVENT		45
// {publishTrigger Pin} 
#define PUBLISH_TRIGGER		46
// {pulse int int int int} 
#define PULSE		47
// {pulseStop} 
#define PULSE_STOP		48
// {read String} 
#define READ		49
// {record} 
#define RECORD		50
// {releaseI2cDevice I2CControl int int} 
#define RELEASE_I2C_DEVICE		51
// {reset} 
#define RESET		52
// {sensorActivate SensorControl Object[]} 
#define SENSOR_ACTIVATE		53
// {sensorDeactivate SensorControl} 
#define SENSOR_DEACTIVATE		54
// {sensorPollingStart String} 
#define SENSOR_POLLING_START		55
// {sensorPollingStop String} 
#define SENSOR_POLLING_STOP		56
// {servoAttach ServoControl int} 
#define SERVO_ATTACH		57
// {servoDetach ServoControl} 
#define SERVO_DETACH		58
// {servoSetMaxVelocity ServoControl} 
#define SERVO_SET_MAX_VELOCITY		59
// {servoSetVelocity ServoControl} 
#define SERVO_SET_VELOCITY		60
// {servoSweepStart ServoControl} 
#define SERVO_SWEEP_START		61
// {servoSweepStop ServoControl} 
#define SERVO_SWEEP_STOP		62
// {servoWrite ServoControl} 
#define SERVO_WRITE		63
// {servoWriteMicroseconds ServoControl int} 
#define SERVO_WRITE_MICROSECONDS		64
// {setBoardMegaADK} 
#define SET_BOARD_MEGA_ADK		65
// {setDebounce int} 
#define SET_DEBOUNCE		66
// {setDebug boolean} 
#define SET_DEBUG		67
// {setDigitalTriggerOnly Boolean} 
#define SET_DIGITAL_TRIGGER_ONLY		68
// {setFormat String} 
#define SET_FORMAT		69
// {setSerialRate int} 
#define SET_SERIAL_RATE		70
// {setTrigger int int int} 
#define SET_TRIGGER		71
// {softReset} 
#define SOFT_RESET		72
// {stopRecording} 
#define STOP_RECORDING		73
// {unsetController} 
#define UNSET_CONTROLLER		74
// {write int int} 
#define WRITE		75
///// INO GENERATED DEFINITION END //////


/*******************************************************************
 * serial protocol functions
 */
#define MAGIC_NUMBER            170 // 10101010


/*******************************************************************
 * BOARD TYPE
 */
#define BOARD_TYPE_ID_UNKNOWN 0
#define BOARD_TYPE_ID_MEGA    1
#define BOARD_TYPE_ID_UNO     2

#if defined(ARDUINO_AVR_MEGA2560) || defined(ARDUINO_AVR_ADK)
  #define BOARD BOARD_TYPE_ID_MEGA
#elif defined(ARDUINO_AVR_UNO)
  #define BOARD BOARD_TYPE_ID_UNO
#else
  #define BOARD BOARD_TYPE_ID_UNKNOWN
#endif

#endif
